//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int IDNews { get; set; }
        public string Tieude { get; set; }
        public Nullable<int> IDCategory { get; set; }
        public string Chitiet { get; set; }
        public string Nguoitao { get; set; }
        public string Image { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
