//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour
    {
        public int IdTour { get; set; }
        public string NameTour { get; set; }
        public Nullable<int> Price { get; set; }
        public string Images { get; set; }
        public Nullable<int> Stars { get; set; }
        public Nullable<int> Review { get; set; }
        public Nullable<int> Distance { get; set; }
        public string Location { get; set; }
    }
}
